### ISSUE TITLE
Unable to add SpotifyKit via Carthage

### ISSUE THREAD

**Issue by malonehedges** [haversnail/SpotifyKit#1]
I am getting this error after adding the line to my `Cartfile` as indicted in the README and running `carthage update`:
```
Failed to check out repository into /Users/malone/Library/Caches/org.carthage.CarthageKit/dependencies/ios-sdk: No object named "beta-25" exists (Error Domain=CarthageKit.CarthageError Code=24 "(null)")
```

**Comment by groebe1kenobi** [comment]
Hello, I have also been experiencing the same issues. Would really like to use this framework as well.

**Comment by haversnail** [comment]
Thanks for raising this issue @malonehedges, and apologies for the delayed response. Unfortunately this framework was built around Spotify's legacy streaming SDK, which appears to have been replaced wholesale by their new metadata-focused [SDK](https://github.com/spotify/ios-sdk) (which is why version `beta-25` no longer exists). As a result, I will be archiving this repository; however, if you see value in maintaining/refactoring, feel free to fork. I appreciate your interest!
